### ISSUE TITLE
Scanning of biological cultures

### ISSUE THREAD

**Issue by MariaSyn** [bqlabs/horus#61]
Hello!

I bought Ciclop 3D Scanner since a few weeks for a project we are working on and I have many questions.
(1) I want to detect cultures on petri dishes but the scanner does not give good models for objects less than 5x5cm. So what can I do to detect really small objects? Will it help if I change the camera? (or maybe the lasers?)
(2) A big problem is that my petri dishes are really reflective since there is medium on them. Is it possible to scan reflective surfaces without using a spray? 
(3) What can I do to have less noise from the various reflections in the room? I tried a black background and I also tried to put the whole device in a box. But if I put it in a box, I still have reflections from the box. I want to try a antireflection spray. Any other ideas?

In all cases I tried playing with the threshold, laser triangulation, platform extrinsics, brightness, contrast, exposure etc.

Any advice would be helpful.
Thank you!

**Comment by Jesus89** [comment]
Hi!
1. Using a camera with more resolution will increase the resolution in the scanner. You can try to adjust the focus of the current C270 camera.
2. Laser scanners doesn't get along with reflective surfaces. You can use some white powder spray.
3. In order to reduce the noise you can adjust "open" parameter and also "threshold" in order to reduce the noise.
Probably, in this case, a linear laser scanner could be interesting.
Regards.
