### ISSUE TITLE
Number of lasers

### ISSUE THREAD

**Issue by ks156** [bqlabs/horus#63]
Hello,

I plan to build a 3D scanner compatible with Horus and the Horus firmware.

The horus firmware is capable to use 4 lasers it seems (https://github.com/bqlabs/horus-fw/blob/develop/laser_control.c#L65-L69), but I'm wondering if horus is capable to handle 4 lasers ? I don't see parameters about the number of lasers in the code.. all seems hardcoded for two.

What would be the difficulty / effort to enable horus to handle 4 lasers, and what would be the real benefits? I'm quite new to 3D scanning and I don't really know if it's really beneficial to increase the number of lasers. Does it affect the scanning accuracy/precision, or the scanning speed, or something else ?

Some expert advices would be appreciated  :smile:

**Comment by Jesus89** [comment]
Hi!

Horus engine is almost compatible with n lasers because it is using vectors of lasers. In GUI more changes will be needed.

I think it is not necessary, because you can scan the object in different positions to increase point cloud data, but better conclusions will be discovered by experimenting.

Regards.

**Comment by ks156** [comment]
Hello @Jesus89,

Thank you for your answer. I was suspecting that the GUI part would require the most important work, and you confirm my first thought.
Anyway, before playing with more than two lasers, I have to build my 3D scanner. Once it's built and works, I'll try to evaluate the effort needed on the code to increase the number of lasers.

BR,

Paul
